【Laravel基礎】「Laravelの基本」〜「環境構築&HelloWorld表示」の作成
shimotaroo/text-kyozai pull request #2
Opened 2021-07-22 05:03 UTC by nakaji0210

## 概要
- 「03Laravel課題(基礎)」のテキスト教材として、「Laravelの基本」〜「環境構築&HelloWorld表示」を新規作成しました。
- 画像ファイルはたくさんありますが、作成したmdファイルは3つです。

## 作成したmdファイル
- 00_Laravelの基本.md →Laravelの概要説明
- 01_LaravelでHello World!を表示する(MacOS).md →MAMP,Composer,Laravelのインストール
- 01_LaravelでHello World!を表示する(Windows).md →XAMPP,Composer,Laravelのインストール

## 申し送り事項
- 教材内で「Windows環境の方はこちら」「MacOS環境の方はこちら」というリンクがありますが、リンクは未設定です。
- そもそも課題本体のほうがWindowsとMacで別々のリンクになっていないはずなので、要調整です。
- PHP編でMAMPやXAMPPをすでにインストールする感じになっていると、内容が完全にぶつかってしまうので要調整です。
- HelloWorldを表示する部分は、既存のウェルカムページの「Laravel」の部分を「HelloWorld」に書き換えてみる程度にしていいます。

2021-07-22 07:28 UTC, shimotaroo requested changes
Windows向けはMac向けの修正と同じです

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +これからアプリケーションを開発していく前に、まずはLaravelがどういうものなのかについて説明していきます。
これからPHPフレームワークのLaravelでアプリケーションを開発していく前に

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +フレームワークには基本となるファイル構成やプログラム機能が備わっており、開発者は必要に応じてプログラムファイルを追加したり編集していくことにより、目的のアプリケーションを最短で構築することができます。
最短で　→ 手軽に

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +国内でもPHPアプリケーションの新規開発は、かなりの割合でLaravelの案件になってきているので、これから学ばれる方はLaravelを集中して習得するのが良いでしょう。
国内でもPHPを使用したWebアプリケーションの新規開発は、かなりの割合でLaravelの案件になってきているので、現在PHPを学習している方はLaravelを選択して習得するのが良いでしょう。

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +作成されたBladeテンプレートはBladeエンジンによりレンダリングされ、コントローラを介してブラウザにHTMLとして表示されます。
この後に

Blade、テンプレート、エンジン、レンダリングなど馴染みのない言葉が急に現れて混乱しているかもしれませんが、今はLaravelには画面（ページ）を作成するために便利な機能があらかじめ備わっていると思っておいて問題ありません。

的なやつ入れて欲しいです。（適宜修正OK）

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +これはデータベースに想定外の形式のデータが登録されるのを防ぐためにも重要なことです。
これは　→　バリデーションとは

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/00_Laravelの基本.md
> +LaravelにはPHP Unitと呼ばれるテスト機能が標準で備わっています。
PHP Unit（半角スペース）

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/01_LaravelでHello World!を表示する(MacOS).md
> +Laravelのアプリケーションを開発してWebブラウザで動かすためには、ローカルのWebサーバーやデータベースサーバーが必要になります。
ローカル　→　ローカル（皆さんが使っているPCの中）

2021-07-22 07:28 UTC, shimotaroo commented on 01_Laravel基礎/01_LaravelでHello World!を表示する(MacOS).md
> +「Webサーバー＋データベースサーバー＋PHP」などを一括インストールするパッケージです。(マンプ/ザンプと読みます)
Webアプリケーションを構成するミドルウェアである

- Webサーバー
- データベースサーバー
- PHP

などを

2021-07-22 22:33 UTC, nakaji0210 commented on 01_Laravel基礎/00_Laravelの基本.md
> +作成されたBladeテンプレートはBladeエンジンによりレンダリングされ、コントローラを介してブラウザにHTMLとして表示されます。
→適宜いい感じにしつつ追記しました！

2021-07-22 22:34 UTC, nakaji0210 commented on 01_Laravel基礎/00_Laravelの基本.md
> +これはデータベースに想定外の形式のデータが登録されるのを防ぐためにも重要なことです。
「これは」→「これをバリデーションといいますが」

としました！

2021-07-22 22:34 UTC, nakaji0210 commented on 01_Laravel基礎/00_Laravelの基本.md
> +LaravelにはPHP Unitと呼ばれるテスト機能が標準で備わっています。
「」で括って、「PHP Unit」としました。

（より見やすく）

2021-07-23 01:03 UTC, shimotaroo approved these changes

2021-07-23 01:03 UTC, merged