ログイン・ユーザー登録（ジーコ）
shimotaroo/text-kyozai pull request #7
Opened 2021-07-27 14:33 UTC by ziko7110

ログイン・ユーザー登録（laravel ui）の作成

bootstrapにてログイン機能実装
```
php artisan ui bootstrap
```

2021-07-27 14:38 UTC, ziko7110 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +resources/views/auth/login.blade.php
ここ、正しくは`resources/views/auth`ですね。直しときます。

2021-07-27 23:05 UTC, nakaji0210 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +
いつも横からすません🙏
`--auth`オプションが必要なのと、このあとにnpmの導入と`npm install && npm run dev`が必要と思いました。。

2021-07-27 23:08 UTC, nakaji0210 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +
DB接続編でUser関連のテーブルはMigrateしてあるという前提でしょかね

2021-07-27 23:59 UTC, shimotaroo requested changes

2021-07-27 23:59 UTC, shimotaroo commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +|RegisterController.php|新規登録時に使用するコントローラー|
Controller、Laravel6ってlaravel ui使わなくてもデフォルトで準備されている気が

2021-07-27 23:59 UTC, shimotaroo commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +
```
Laravelでは簡単にログイン・ユーザー登録などの認証機能が実装できます。<br>
認証機能に必要なファイルはほとんど最初から準備されいます。<br>
コマンド1つで新規登録ページ,　新規登録機能,　ログインページ,　ログイン機能などが作成されます。<br>
```
これ始めに入れる

2021-07-27 23:59 UTC, shimotaroo commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +コマンド1つで新規登録ページ,　新規登録機能,　ログインページ,　ログイン機能などが作成されます。<br>
消す

2021-07-28 04:07 UTC, nakaji0210 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +|RegisterController.php|新規登録時に使用するコントローラー|
たしかに、`laravel ui`コマンドで追加されるコントローラーはHomeControllerだけですね🤔

2021-07-28 14:06 UTC, ziko7110 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +
--auth 必要ですね！失礼しました！汗

2021-07-28 14:06 UTC, ziko7110 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +
ここはMigrateしてある前提です！マイグレーション編のマイグレーション後でも実装できたので問題ないと思います！

2021-07-28 14:06 UTC, ziko7110 commented on 01_Laravel基礎/ログイン・ユーザー登録.md
> +|RegisterController.php|新規登録時に使用するコントローラー|
新たにプロジェクト作成して検証しましたが既に入っていた。。。これは勉強不足でした。すません。。

2021-07-29 00:08 UTC, shimotaroo approved these changes

2021-07-29 00:08 UTC, merged