LaravelのCRUDアプリの前編を作成
shimotaroo/text-kyozai pull request #9
Opened 2021-08-02 04:14 UTC by nakaji0210

## 概要およびやったこと
- 「LaravelでCRUDアプリを実装する」の前編として、投稿機能までのパートを作成しました。
- 当初はCRUDで4つのパートにする予定でしたが、投稿機能を実装するまでがかなりボリュームが大きかった(モデル作成〜投稿〜バリデーションまである)ため前編と後編という構成にしています。

## 申し送り
- 後編は今回mdファイルの作成(見出しのみ)だけしてある状態なので、そのまま同じブランチで作業してまいります。
- 後編は一覧表示と編集削除の実装です。

2021-08-02 13:55 UTC, shimotaroo requested changes

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +`$fillable`のところで、postsテーブルにおいて書き換えが可能なカラムを指定しています。
`$fillable`にはユーザー入力値の中でデータベースに登録した情報を指定しています。今回は`titile`、`body`カラムを指定しています。

※ここ説明難しい...w

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +投稿のidはユーザーが編集することはできないですが、タイトルや本文は書き換え可能とするためです。
投稿データのの`id`カラムの値は自動で割り振られるのですが、タイトル(title)や本文(body)はユーザー入力値によって登録したり編集したりできるようにします。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +「１人のユーザーが多数の投稿を持つ」という定義をしていることになるのですが、これにより後ほど作成する投稿処理において、どのユーザーが投稿したものかを取得できるようになります。
```
    // Userモデルとのリレーション
    public function user()
    {
        return $this->belongsTo('App\User');
    }
```
については、モデル間のリレーションを定義しています。
上記の`belongsTo()`メソッドでUserモデルと多対１の関係のもつことを表します。

「1人のユーザーは0以上の複数の投稿を持つ」という関係性を定義をしています。

これは投稿データ登録後に画面に表示する際に、手軽に「投稿したユーザーの情報」を取得することができます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +<br>
131〜163行目は不要です。

ユーザーが投稿したデータは取得する必要がないです。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +次に、投稿機能(登録処理)についてのルーティングを追記していきましょう。
まずはルーティングを定義します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これには`routes/web.php`を編集していきます。
`routes/web.php`を以下のとおり編集します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +Route::get('/home', 'HomeController@index')->name('home');
// 略

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +});
resourceメソッドを使ってください。
課題の内容と照らし合わせる
https://github.com/shimotaroo/yanbaru-kadai/blob/main/5_Laravel%E8%AA%B2%E9%A1%8C%EF%BC%88%E5%BF%9C%E7%94%A8%EF%BC%89.md

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +<br>
- ここも適宜修正
- ルーティングの確認作業を追加

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +ルーティングが定義できたら、処理の要であるコントローラーを作成していきましょう。
モデルを作成したらコントローラーを作成します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +投稿テーブルは「posts」というテーブル名で定義したので、コントローラーは「PostController」という名前で作成します。
基本的に「」ではなくバッククォートの方がmdぽいです

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +では、ターミナルにて以下のコマンドを実行してコントローラーを作成します。
ターミナルで以下のコマンドを実行してコントローラーを作成します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これで`app/Http/Controllers`というディレクトリの中に`PostController.php`が作成されているはずですので、VSCodeのツリーから確認してみましょう。
コマンドを実行することで`app/Http/Controllers`ディレクトリの中に`PostController.php`が作成されます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +ここでは、ルーティングで作成した「投稿画面の表示」と「登録処理」を作成します。
実際にコントローラーに処理を実装していきます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +・app/Http/Controllers/PostController.php
`app/Http/Controllers/PostController.php`を以下の通り修正します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +    // 新規投稿画面を表示するアクション
登録（投稿）画面表示

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +    // 新規投稿して保存するアクション
登録（投稿）処理

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +        $post->user_id = Auth::id(); // 現在のログインユーザーのIDを格納
Auth::id()でログインユーザーのIDが取得できる

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +        return redirect()->route('post.create');
```
return redirect()->route('index');
```
トップページにリダイレクトさせましょう！
トップページは超簡易的なものでOKです。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +おおよそやっていることを理解しつつコントローラーが実装できたら、続いてビューを実装していきましょう。
いきましょう。→ いきます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +モデルとコントローラーができましたので、最後に投稿画面を実装していきます。
モデルとコントローラーができたので、ビュー（画面）を作成します。

以下の2つの画面を作成します。

- トップページ（投稿データを表示する）
- 投稿画面

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +まずは`resources/views`の直下に「post.blade.php」というファイルを新規作成しましょう。
`resources/views`の直下に`post`ディレクトリを作成し、その中に`create.blade.php`を新規作成します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +・resources/views/post.blade.php
`resources/views/post/create.blade.php`を以下のとおり編集します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +- 投稿のformにおいては、Postメソッドで`posts.store`という名前のルートを指定しています。これは先ほどルーティングの`web.php`で記載しているので、そこで定義したアクション(`store`アクション)が実行されることになります。
Postメソッド？？w

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +こちらもなんとなくやっていることを理解しつつ実装できたら、今度はブラウザで動作を確認してみましょう。
なんとなくとかいう文言は入れないほうが良いので削除

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +現在の投稿画面では、タイトルや本文を入力しない状態で「投稿する」ボタンを押しても投稿ができてしまいます。(実際にはSQLのエラーとなります)
投稿ができてしまいます。　→ 　登録処理が実行されてしまいます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +そこで投稿機能には「バリデーション」というものを追加実装します。
そこでユーザーが入力した値が正しいかどうかを判定するためにバリデーションを実装します。

※編集にもありますw

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +Laravelにおいてはフォームリクエストという機能があるのでこれを利用しましょう。
Laravelではバリデーションを実装する方法はいくつかあるのですが、使われることの多い、「フォームリクエスト」という機能を利用します。
（ReadoubleのバリデーションページのURL）

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +以下のコマンドを実行することでフォームリクエストを作成します。
ターミナルで以下コマンドを実行し、投稿データ用のフォームリクエストを作成します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +・app/Http/Requests/PostRequest.php
作成した`app/Http/Requests/PostRequest.php`を以下の通り修正します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +次に、今作成したフォームリクエストをコントローラーにて利用できるように設定反映する必要があります。
フォームリクエストを準備できたらコントローラーで利用できるように設定する必要があります。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +・app/Http/Controllers/PostController.php(抜粋)
`app/Http/Controllers/PostController.php`の`store`メソッドを以下の通り編集します。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +public function store(PostRequest $request) // 「Request」→「PostRequest」に変更
コメントの「」は不要

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +    〜略〜
// 略

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +
このように修正することで登録処理の初めにフォームリクエストによるバリデーションが行われて、条件を満たさないデータは登録できないようにすることができます。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +
表を使って

- ttile
- body

のバリデーション内容を追加

必須、20文字以内
とかでOKです

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +
トップ画面の説明も簡単に入れる。
画面のコードを載せてこの通りに実装してトップ画面を作成しますくらいの説明でOK

※foreachの説明はあったほうがいいですねw

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +ですので、投稿画面にバリデーション時のエラーメッセージが表示されるようにしましょう。
ただし、現在の投稿画面にはバリデーションによって弾かれた場合に画面にエラーメッセージが表示されないので表示されるようにする必要があります。

2021-08-02 13:55 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これにはまず、エラーメッセージのBladeファイルを作成します。
ここは切り出したいところですが、今回は投稿画面にベタ書きでいきましょう。。

編集画面で切り出したほうが自然かなと思いましたがどうでしょうか？
（共通で使えそうだから切り出そう、的な）

2021-08-02 21:10 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これにはまず、エラーメッセージのBladeファイルを作成します。
確かに今の状態だとちょっと不自然かもですね。。

「このあと実装する編集機能でも共通で使いたいので、」
とか理由つけて、ここで１発で片付ける感じにしたいという想いがありますw

2021-08-02 21:11 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +- 投稿のformにおいては、Postメソッドで`posts.store`という名前のルートを指定しています。これは先ほどルーティングの`web.php`で記載しているので、そこで定義したアクション(`store`アクション)が実行されることになります。
「POST通信」が良いですねw

2021-08-02 21:16 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +});
ここのルーティングとコントローラーなのですが..
確かに今の課題とずれってしまっているのですが「受講生に自分の手でルーティングの書き方やコントローラー実装を覚えてもらいたい」みたいな想いから、手動で作成する方向に(課題も含めて)したいと思っているのですが難しいすかね？🤔

2021-08-02 22:45 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +`$fillable`のところで、postsテーブルにおいて書き換えが可能なカラムを指定しています。
`$fillable`には、データベースにおいてユーザーが入力できる値のカラムを指定します。今回は`title`と`body`カラムを指定しています。

でいきます！(たしかに説明むずいすねw)

2021-08-03 03:10 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +});
→メモ：Slackのやりとりにて以下の方針とする
- 現状の手作りのルーティングのままとするが、RESTになっていないので修正。
- 課題の方はこれに合わせて追って内容を変更する。

2021-08-03 03:12 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +        return redirect()->route('post.create');
→メモ：Slackのやりとりにて以下の方針とする
- 投稿一覧も登録機能と併せて一緒に実装する形にする
- 最初から投稿一覧にリダイレクトするようにする

2021-08-03 03:16 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これにはまず、エラーメッセージのBladeファイルを作成します。
→メモ：Slackのやりとりにて以下の方針とする
- 最初からerrorメッセージのblade切り出してもOK
- ただし、なぜそうするのかを理解できるように自然な形で説明する

2021-08-04 04:10 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能」.md
> +これにはまず、エラーメッセージのBladeファイルを作成します。
→メモ追記
- ここは結局「投稿画面にベタ書き」としました。
※バリデーションを先に持ってくる構成としたため、errorメッセージのblade切り出すのは不自然になる

2021-08-04 13:37 UTC, shimotaroo requested changes

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +今回は、まずは登録機能（C:Create）と読込・表示機能（R:Read）までを実装していきます。
一覧表示はRではないので、CだけでOKです。
次の課題で詳細画面の説明です。

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +→[MVCアーキテクチャ](https://github.com/shimotaroo/text-kyozai/blob/main/01_Laravel%E5%9F%BA%E7%A4%8E/00_Laravel%E3%81%AE%E5%9F%BA%E6%9C%AC.md#mvc%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83
ここはテキスト教材「Laravelの基礎」のリンクを貼るだけでOK

<hr>

MVCの理解がまだ浅い方はこちらの教材で軽くおさらいしておくと、今回の内容をより理解しやすくなります。

URL

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +// 〜前略〜
// 略

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +// ---この部分は削除---
// ---ここから削除---

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +// ---以下を最後に追記---
// 追記

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +- `'middleware' => 'auth'`の部分で「ログインした状態じゃないとアクセスできない」という設定をしています。
`['middleware' => 'auth']`

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +- この`name`をつけておくと、コントローラーなどでルート名を指定して実行することができるようになります。
この1文削除

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +Laravelでデータベースを操作するには、基本的にモデルの`ORM（Eloquent）`というものを通して行うため、まず最初にモデルを作成することが基本となります。
LaravelではMVCのMにあたるModelからORM（Eloquant）を通してデータベースを操作するので、まずはモデルを作成します。

前回レビュー通り84〜86行目を上記に修正

> モデルの`ORM（Eloquent）`

という言い回しは違和感がw

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +コマンドを実行することで`app/Http/Controllers`というディレクトリの中に`PostController.php`が作成されます。
「という」は不要

こういう冗長な表現はなるべく無くして欲しいです！！

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +
空行消す

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +            'body' => 'required|max:20', // 本文に関するルールを記述
bodyは140

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +                                </a>
詳細画面から編集・削除が行えるようにしたいのでここは詳細画面へのリンクとして「詳細」のみ表示に変更してください。

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +        {{ $posts->links() }}
ページネーションは不要です

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +        $posts = Post::paginate(5);
ここは全件表示にしておきましょう。
ページネーションは別の教材で

```
$posts = Post::all();
```

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +- `@if`の部分もそうですが、このようにBladeのディレクティブを用いてPHPのif文やforeach文と同様に制御構造を記述することができます。
baldeファイルでは`@if`、`@endif`のようにif文やforeach文を表現します。

2021-08-04 13:37 UTC, shimotaroo commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +- なお編集ボタンと削除ボタンの挙動はあとで実装するので、この段階では指定しなくてOKです。(`"#"`としています)
なお編集ボタンと削除ボタンの挙動は　→　詳細ボタンから詳細画面への遷移は

2021-08-04 22:33 UTC, nakaji0210 commented on 02_Laravel応用/x1_LaravelでCRUDアプリを実装する(前編)「投稿機能・一覧表示」.md
> +Laravelでデータベースを操作するには、基本的にモデルの`ORM（Eloquent）`というものを通して行うため、まず最初にモデルを作成することが基本となります。
ここはめっちゃ迷いましたが..たしかに違和感すねw

そのままレビューを反映すると「モデルを作成します」が３行連続してしまうので以下のようにします。

> ルーティングの定義ができたら、MVCのMにあたるモデル(Model)を作成します。
> LaravelではモデルからORM（Eloquent）を通してデータベースを操作するので、それに対応するモデルが必要です。
> ここでは投稿データを保存するためのpostsテーブルに対応するPostモデルを作成します。(UserモデルはLaravelがデフォルトで準備してくれています)

また最後の文は、Userモデルの説明が前にあると文章が長くて読みづらい感があったので( )内で補足する形としています。

2021-08-05 12:51 UTC, shimotaroo approved these changes

2021-08-05 12:51 UTC, merged